config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get 'home/index'
  resources :candidates
  resources :superadmins
  resources :admins
  devise_for :users

  root to: 'home#index'

  namespace :admin do
    resources :offers do
      member do
        get :posts
      end
    end
  end


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/admin.rb
class Admin < User
  belongs_to :company

  has_many :offers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < User
  has_many :posts, foreign_key: :user_id
  has_many :offers, through: :posts
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :superadmins
  has_many :admins

  has_many :offers
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :company
  belongs_to :admin, foreign_key: :user_id, optional: true
  belongs_to :superadmin, foreign_key: :user_id, optional: true

  has_many :posts
  has_many :candidates, through: :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :candidate, class_name: 'User', foreign_key: :user_id
  belongs_to :offer
end

app/models/superadmin.rb
class Superadmin < User
  belongs_to :company
  has_many :offers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < ApplicationController
  before_action :authorize_only_admin!
  before_action :set_offer, only: %i[show edit update destroy]

  # GET /offers
  def index
    if current_user.type = "Superadmin"
      @offers = current_user.company.offers
    else
      @offers = current_user.offers
    end
    respond_to do |format|
      format.html # This will look for app/views/admin/offers/index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  def show
  end

  def posts
    @offer= Offer.find(params[:id])

    @users = @offer.candidates
    respond_to do |format|
      format.html # This will look for app/views/admin/offers/index.html.erb
      format.json { render json: [@offer, @users] }
    end
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/:id/edit
  def edit
  end

  # POST /offers
  def create
    @offer = Offer.new(offer_params)

    @offer.user_id = current_user.id
    @offer.company_id = current_user.company.id

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.turbo_stream {
          redirect_to admin_offers_path
        }

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace('offer_form', partial: 'admin/offers/form',
                  locals: { offer: @offer, title: "New offer" })
        }
      end
    end
  end

  # PATCH/PUT /offers/:id
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace('offer_form', partial: 'admin/offers/form',
                  locals: { offer: @offer, title: "Edit offer" })
        }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace('offer_form', partial: 'admin/offers/form',
                  locals: { offer: @offer })
        }
      end
    end
  end

  # DELETE /offers/:id
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.turbo_stream { render turbo_stream: turbo_stream.remove("offer_#{@offer.id}") }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def offer_params
    params.require(:offer).permit(:title, :description, :expired_date, :limit_date, tags: []).tap do |offer_params|
      offer_params[:tags] = offer_params[:tags].split(',').map(&:strip) if offer_params[:tags].is_a?(String)
    end
  end

  # other actions (show, new, create, edit, update, destroy) can be defined here
end

app/controllers/admins_controller.rb
class AdminsController < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action  :authenticate_user!

  def authorize_only_admin!
    redirect_to root_path, notice: 'Non autorisé!' unless current_user.type == "Admin" || current_user.type == "Superadmin"
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < User
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

end

app/controllers/superadmins_controller.rb
class SuperadminsController < User
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/superadmins_helper.rb
module SuperadminsHelper
end

app/views/admin/offers/_form.html.erb
<%= form_with(model: [:admin, offer], local: false, id: "offer_form") do |form| %>
  <h1><%= title %></h1>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mb-2">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class:"form-control", rows:5 %>
  </div>

  <div class="mb-2">
    <%= form.label :expired_date, class:"form-label" %>
    <input type="date" name="offer[expired_date]" value="<%= offer.expired_date || Date.current %>", class="form-control">
  </div>

  <div class="mb-2">
    <%= form.label :limit_date, class:"form-label" %>
    <input type="date" name="offer[limit_date]" value="<%= offer.limit_date || Date.current %>", class="form-control">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/offers/edit.html.erb
<div class="col-12 col-md-6 offset-md-3 mt-5">
  <%= render "admin/offers/form", offer: @offer, title: "Edit offer" %>
</div>

app/views/admin/offers/index.html.erb
<h1>
  Our Offers
</h1>

<% @offers.each do |offer| %>
  <div>
    <%= offer.title %>
    <%= link_to 'Edit', edit_admin_offer_path(offer)%>
    <%= link_to 'Posts', posts_admin_offer_path(offer)%>
  </div>
<% end %>

app/views/admin/offers/new.html.erb
<div class="col-12 col-md-6 offset-md-3 mt-5">
  <%= render "admin/offers/form", offer: @offer, title: "New offer" %>
</div>

app/views/admin/offers/posts.html.erb
<h1>
  Posts of <%= @offer.title %>
</h1>

<% @users.each do |user| %>
  <div>
    <%= user.to_json %>
    <%= link_to 'Back', admin_offers_path%>
  </div>
<% end %>

app/views/offers/_form.html.erb
<%= form_with(model: offer, local: false, id: "offer_form") do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mb-2">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_area :description, class:"form-control", rows:5 %>
  </div>

  <div class="mb-2">
    <%= form.label :expired_date, class:"form-label" %>
    <input type="date" name="offer[expired_date]" value="<%= Date.current %>", class="form-control">
  </div>

  <div class="mb-2">
    <%= form.label :limit_date, class:"form-label" %>
    <input type="date" name="offer[limit_date]" value="<%= Date.current %>", class="form-control">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/index.html.erb
<h1>
  Public Offers
</h1>