config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get 'home/index'
  resources :candidates
  resources :superadmins
  resources :admins
  devise_for :users

  root to: 'home#index'

  namespace :admin do
    resources :offers do
      member do
        get :posts
      end
    end
  end


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/admin.rb
class Admin < User
  belongs_to :company

  has_many :offers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < User
  has_many :posts, foreign_key: :user_id
  has_many :offers, through: :posts
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :superadmins
  has_many :admins

  has_many :offers
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :company
  belongs_to :admin, foreign_key: :user_id, optional: true
  belongs_to :superadmin, foreign_key: :user_id, optional: true

  has_many :posts
  has_many :candidates, through: :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :candidate, class_name: 'User', foreign_key: :user_id
  belongs_to :offer
end

app/models/superadmin.rb
class Superadmin < User
  belongs_to :company
  has_many :offers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/admins_controller.rb
class AdminsController < User
end

app/controllers/candidates_controller.rb
class CandidatesController < User
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/superadmins_helper.rb
module SuperadminsHelper
end

app/views/layouts/_header.html.erb
<header class="p-3 bg-dark text-white main-header">
	<div class="container-fluid">
		<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
			<a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
				<%= image_tag 'logo.png', class:"logo" %>
			</a>

			<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
				<li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
				<li><a href="#" class="nav-link px-2 text-white">Features</a></li>
				<li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
				<li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
				<li><a href="#" class="nav-link px-2 text-white">About</a></li>
			</ul>

			<form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
				<input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
			</form>


			<div class="text-end ms-lg-auto">
				<% if user_signed_in? %>
					<div class="flex-shrink-0 dropdown">
						<a href="#" class="d-block link-dark text-decoration-none" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="true">
							<%= image_tag 'avatar.png', class:"rounded-circle avatar-profile" %>
						</a>
						<ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(-112px, 34px);" data-popper-placement="bottom-end">
							<li><a class="dropdown-item" href="#">New project...</a></li>
							<li>
								<%= link_to 'Offers', admin_offers_path, class: "dropdown-item" %>
							</li>
							<li>
								<%= link_to 'New offer', new_admin_offer_path, class: "dropdown-item" %>
							</li>
							<li><a class="dropdown-item" href="#">Profile</a></li>
							<li><hr class="dropdown-divider"></li>
							<li>
								<%= link_to 'Sign Out', destroy_user_session_path, class:"dropdown-item text-danger" , method: :delete, data: { turbo_method: :delete, confirm: 'Are you sure you want to sign out?' } %>
							</li>
						</ul>
					</div>

				<% else %>
					<%= link_to 'Sign in', new_user_session_path, class: "btn btn-outline-light me-2" %>
					<%= link_to 'Sign up', new_user_registration_path, class:"btn btn-warning" %>
				<% end %>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_notice.html.erb
<% flash.each do |msg_type, message| %>
  <div id="notice-message" class="notice-message <%= msg_type %>">
    <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeteoJob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/notice" %>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>